### ISSUE TITLE
Improve diff performance

### ISSUE THREAD

**Issue by craigds** [koordinates/sno#156]
`Dataset1.diff()` is currently quite slow on large datasets/diffs (e.g. _minutes_ on an import commit with 2M rows). What's more, it doesn't return until it has processed all the deltas and done rename detection on them.

It'd be helpful if it was incremental, so we could start streaming output into a pager earlier. That would probably require:

 - pushing rename detection down into pygit2 if possible (?)
 - making sno.diff.Diff evaluate pygit2 deltas lazily.

**Comment by olsen232** [comment]
Dataset2.diff() is basically exactly the same, it uses the same code (but delegates to Dataset2.get_feature which could be more or less efficient than Dataset1, I haven't really investigated). Certainly, diff times are very similar for v1 vs v2.

The rename detection is part of the problem. But to structure it a bit more formally, we have two main problems:
1. We buffer every delta before we show any delta
2. Generating and outputting deltas is slow

The first problem can be broken into several subproblems - several things that were easiest to do by just buffering everything first, and doing it an other way will require a lot more cunning:
1a) Concatenating two diffs together before output is needed for a diff like `sno diff HEAD^` which diffs HEAD^<>HEAD<>working-copy. The way this works currently is by generating both diffs, then concatenating the deltas that affect the same keys. All of this happens before a single delta is output
1b) Rename detection - we generate all insert deltas, and all delete deltas, and then we try to match them up as rename deltas. The code to do this seems to be pretty efficient but again, it means all deltas are generated before any are output
1c) Diffs are roughly structured as nested dicts - `{dataset1: {feature: {pk1: {...}, pk2: {...}}}`. Need to code more carefully to make them output faster by making them "nested dicts except the innermost dict doesn't have to be fully generated when we start iterating"
1d) Sort order. Right now output is sorted by primary key, which again, involves generating all deltas before showing any of them.

Solutions for problem(s) 1:
- Solution S1 - the simpler one
Lazily create delta features - instead of having a delta that looks like (old_pk, old_feature) -> (new_pk, new_feature), a delta could be generated as (old_pk, old_blob) -> (new_pk, new_blob). The blobs would be pygit2.Blob objects or similar. This means we could do most of the stages we do above before the output step, but put off actually reading the blob content until the output step.

- Solution S2 - more complex, but might be faster than S1
 Lazily create deltas - instead of creating all deltas and putting them in a dict, we could write a generator that yields deltas. However, that stops us from doing any of the things above, except that we could use some or all of the following workarounds:

1a) Concatenation - we could generate deltas using a generator for one side of the diff expression, perhaps the larger side, or perhaps always the commit side (eg HEAD^<>HEAD) - and generate the deltas eagerly for the other side of the diff expression (eg HEAD<>working-copy). Then as we iterate through the generator, we can concatenate the eagerly generated deltas as appropriate.
1b) Rename detection. Perhaps git can do rename detection more efficiently than we can, so we needn't iterate through everything ourselves to do it?
1c) The problem / fix here is just the code will no longer be as simple - we can't just say a repo diff is a dict of dataset diffs, which are dicts of delta diffs, which are dicts of deltas. A more heterogenous structure will be needed, one where you can't just query "what is the delta at datasetA:feature:pk=2" - instead you would have to iterate through everything to find it.
1d) The workaround here would be either to abandon having diffs in primary key order (this makes testing a bit more annoying and makes life a bit more confusing for the user), or, find some way of iterating through the git blobs in primary key order. Perhaps there is a different PK hashing function we can use that preserves sort order, but this is actually a hard problem - given some keys in some distribution in key-space K, hash them so that they have a uniform distribution but are in the same order in filename-space F.

I don't have any plans for how to make the code faster overall (problem 2), except by profiling get_feature and seeing what can be done.

**Comment by olsen232** [comment]
Renamed to "improve diff performance" since the diffs are now streamed - at least the expensive pygit2.Blob.data call for each feature only happens once the previous feature has already been output
